[package]
name = "rustcli"
version = "0.1.0"
authors = ["Zou Xinyao <zou.xinyao@outlook.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
